config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :lists
    resources :board_invitations
  end

  resources :tasks, only: [:edit, :show]
  resources :lists do
    put :sort, on: :member
    resources :tasks do
      put :sort, on: :member
    end
  end
  devise_for :users
  get "/invite/accept", to: "board_invitations#accept", as: :accept_invitation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks, dependent: :destroy
  validates :name, presence: true

  include RankedModel
  ranks :row_order, with_same: [:board_id]
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  # GET /lists or /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  def sort
    list = List.find(params[:id])
    list.update(row_order_position: params[:row_order_position])

    head :no_content
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    @list = List.new(list_params)
    @list.board = current_board

    respond_to do |format|
      if @list.save
        @lists = current_board.lists.includes(:tasks).rank(:row_order) if current_board
        format.turbo_stream
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy!

    respond_to do |format|
      format.html { redirect_to lists_path, status: :see_other, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.expect(list: [ :name, :board_id ])
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with(model: list, html: { data: { controller: 'form-actions' } }) do |form| %>
  <%= form.text_field :name, 
                      class: 'rounded rounded-xl p-2 my-2 bg-gray-200 focus:border-sky-400 cursor-pointer max-w-60 hover:bg-gray-300',
                      placeholder: '+ Add a List',
                      autocomplete: false,
                      data: { action: 'focus->form-actions#showActionButtons'}
  %>
  
  <div class="form-actions hidden" data-form-actions-target="actions">
    <%= form.submit 'Add', class: 'rounded-full bg-sky-500 px-3 py-2 text-sm leading-5 font-semibold text-white hover:bg-sky-700 cursor-pointer' %>
    <%= link_to 'Cancel', 'javascript:void(0)', class: 'rounded-full bg-gray-500 px-3 py-2 text-sm leading-5 font-semibold text-white hover:bg-gray-700 cursor-pointer', data: {action: 'click->form-actions#cancel'} %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="border border-gray-300 py-1 p-2 rounded rounded-xl m-1 shadow-md shadow-gray-150 min-w-70 bg-gray-100 cursor-pointer" data-sortable-url="<%=sort_list_path(list)%>" id="lists">
  <div class="relative">
    <b class="text-gray-600 z-[50]"><%= list.name %></b>
  </div>
  
  <div id="tasks_<%=list.id%>" class="py-4" data-controller="sortable" data-sortable-group-value="shared" data-to-list-id=<%=list.id%>>
    <% list.tasks.rank(:row_order).each do |task| %>
      <%= render 'tasks/task', task: task, list: list %>
    <%end%>
  </div>
  <%= turbo_frame_tag "new_task_#{list.id}", src: new_list_task_path(list) %>
</div>

app/views/lists/create.turbo_stream.erb
<%= turbo_stream.update 'current-board-lists' do %>
  <%= render 'boards/current_board_lists', lists: @lists %>
<%end%>

app/views/lists/edit.html.erb
<% content_for :title, "Editing list" %>

<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Lists" %>

<h1>Lists</h1>

<div id="lists">
  <% @lists.each do |list| %>
    <%= render list %>
    <p>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>

<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<%= turbo_frame_tag "new_list" do %>
  <%= render "form", list: @list %>
<%end%>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>