config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :lists
    resources :board_invitations
  end

  resources :tasks, only: [:edit, :show]
  resources :lists do
    put :sort, on: :member
    resources :tasks do
      put :sort, on: :member
    end
  end
  devise_for :users
  get "/invite/accept", to: "board_invitations#accept", as: :accept_invitation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/board_invitation.rb
class BoardInvitation < ApplicationRecord
  enum :status, { pending: 0, accepted: 1, rejected: 2 }

  belongs_to :board
  belongs_to :user

  before_create :generate_token
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :status, inclusion: { in: statuses.keys }

  private

  def generate_token
    self.token = SecureRandom.hex(8)
  end
end

app/controllers/board_invitations_controller.rb
class BoardInvitationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @board = Board.find(params[:board_id])
    invitation = @board.board_invitations.new(invitation_params)
    invitation.user = current_user
    invitation.status = :pending

    respond_to do |format|
      if invitation.save
        BoardInvitationMailer.invite_email(invitation).deliver_now
        format.turbo_stream      
      else
        format.turbo_stream { 
          render turbo_stream: turbo_stream.update('error-message', partial: 'boards/error'), status: :unprocessable_entity 
        }
      end
    end
  end

  def accept
    invitation = BoardInvitation.find_by(token: params[:token])
    
    if invitation&.pending?
      user = User.find_by(email: invitation.email)
      if user
        invitation.update(user: user, status: :accepted)
        flash[:notice] = "You have joined the board!"
        redirect_to root_path
      else
        flash[:alert] = "Invalid invitation."
        redirect_to root_path
      end
    else
      redirect_to root_path, alert: "Invitation is no longer valid."
    end
  end

  private

  def invitation_params
    params.expect(board_invitation: [ :email ])
  end
end

app/helpers/board_invitations_helper.rb
module BoardInvitationsHelper
end

app/views/board_invitations/_form.html.erb
<!-- Modal Background -->
<div data-modal-target="invitationModal" class="absolute inset-0 top-10 hidden z-[999]" data-action="click->modal#close">
  <div class="bg-white p-5 ml-3 rounded-lg shadow-lg max-w-100">
     <%= form_with model: BoardInvitation.new, url: board_board_invitations_path(current_board), method: :post, data: { action: 'click->modal#submit', 'modal-target' => 'form', method: 'post' } do |f| %>
        <%= f.email_field :email, placeholder: "Enter email", class: "border p-2 rounded mb-4 w-full", required: true, data: { 'modal-target' => 'emailInput' }  %>        
        <div class="flex justify-end">
          <%= f.submit 'Send', class: "bg-sky-500 text-white px-2 py-1 rounded cursor-pointer", data: { turbo_disable: true } %>
          <button type="button" data-action-close class="ml-2 bg-gray-400 text-white px-2 py-1 rounded cursor-pointer">Close</button>
        </div>
      <% end %>
  </div>
</div>

app/views/board_invitations/create.turbo_stream.erb
<%= turbo_stream.update 'alert' do %>
  <%= render 'layouts/alert', message: 'Invitation successfully sent' %>
<%end%>