config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :lists
    resources :board_invitations
  end

  resources :tasks, only: [:edit, :show]
  resources :lists do
    put :sort, on: :member
    resources :tasks do
      put :sort, on: :member
    end
  end
  devise_for :users
  get "/invite/accept", to: "board_invitations#accept", as: :accept_invitation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  validates :title, presence: true

  include RankedModel
  ranks :row_order, with_same: [:list_id]
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @list = List.find params[:list_id]

    respond_to do |format|
      format.turbo_stream
      format.html
    end
  end

  def sort
    task = Task.find(params[:id])
    task.row_order_position = params[:row_order_position]
    task.list_id = params[:target_list_id] if params[:target_list_id].present?
    task.save

    head :no_content
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @list = List.find params[:list_id]
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.list_id = params[:list_id]
    respond_to do |format|
      if @task.save!
        @list = @task.list
        format.turbo_stream
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.turbo_stream
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :list_id ])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: [list, task], html: {id: "#{dom_id(task)}_#{list.id}", data: { controller: 'form-actions' } }) do |form| %>
  <%= form.text_field :title, 
                      class: 'rounded rounded-xl p-2 my-2 bg-gray-200 focus:border-sky-400 cursor-pointer max-w-60 hover:bg-gray-300',
                      placeholder: '+ Add a task',
                      autocomplete: false,
                      data: { action: 'focus->form-actions#showActionButtons'}
  %>
  
  <div class="form-actions hidden" data-form-actions-target="actions">
    <%= form.submit 'Add', class: 'rounded-full bg-sky-500 px-3 py-2 text-sm leading-5 font-semibold text-white hover:bg-sky-700 cursor-pointer' %>
    <%= link_to 'Cancel', 'javascript:void(0)', class: 'rounded-full bg-gray-500 px-3 py-2 text-sm leading-5 font-semibold text-white hover:bg-gray-700 cursor-pointer', data: {action: 'click->form-actions#cancel'} %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div 
  id=<%= "#{dom_id(task)}_container" %> 
  class="py-1 bg-white border rounded rounded-xl border-gray-300 p-2 my-2 shadow-md shadow-gray-150 hover:border-blue-400 cursor-pointer relative"
  data-sortable-url="<%= sort_list_task_url(list, task) %>" data-controller="task">
  <%= turbo_frame_tag "edit_task_#{task.id}" do %>
    <div class="w-[215px]"><%= task.title %></div>
    <div class="absolute right-4 top-1">
      <%= link_to 'Edit', edit_task_path(task), class: 'text-gray-300 hover:text-gray-700 text-sm', data: { action: 'click->task#setFocus' } %>
    </div>
  <%end%>
</div>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append "tasks_#{@task.list_id}" do %>
  <%= render partial: "task", locals: { task: @task, list: @list } %>
<%end%>

<%= turbo_stream.replace "new_task_#{@task.list_id}" do %>
  <%= render partial: "tasks/form", locals: { task: Task.new, list: @list } %>
<%end%>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag "edit_task_#{@task.id}" do %>
   <%= form_with(model: @task, url: [@task.list, @task]) do |form| %>
      <%= form.text_area :title, class: 'rounded rounded-xl p-2 my-2 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:border-sky-500 hover:border-gray-400 cursor-pointer max-w-60', "data-task-target" => 'textarea' %>
      
      <div class="form-actions absolute1 right-0 left-0 bottom-" data-form-actions-target="actions">
        <%= form.submit 'Add', class: 'rounded-full bg-sky-500 px-2 py-1 text-sm leading-5 font-semibold text-white hover:bg-sky-700 cursor-pointer' %>
        <%= link_to 'X', '#', class: 'rounded-full bg-gray-500 px-3 py-1 text-sm leading-5 font-semibold text-white hover:bg-gray-700 cursor-pointer' %>
      </div>
    <% end %>
<%end%>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Tasks" %>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<%= turbo_frame_tag "new_task_#{@list.id}" do %>
  <%= render "form", task: @task, list: @list %>
<%end%>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>

app/views/tasks/show.turbo_stream.erb
<%= turbo_stream.replace "tasks_#{@task.list_id}" do %>
  <%= render partial: "task", locals: { task: @task, list: @list } %>
<%end%>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace "#{dom_id(@task)}_container" do %>
  <%= render "tasks/task", task: @task, list: @task.list %>
<% end %>