config/routes.rb
Rails.application.routes.draw do
  resources :boards do
    resources :lists
    resources :board_invitations
  end

  resources :tasks, only: [:edit, :show]
  resources :lists do
    put :sort, on: :member
    resources :tasks do
      put :sort, on: :member
    end
  end
  devise_for :users
  get "/invite/accept", to: "board_invitations#accept", as: :accept_invitation
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "boards#index"
end

app/models/board.rb
class Board < ApplicationRecord
  include RankedModel
  ranks :row_order

  belongs_to :user
  has_many :lists, dependent: :destroy
  has_many :board_invitations, dependent: :destroy
  has_many :invited_users, through: :board_invitations, source: :user

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user_id, message: 'Already taken, must be unique' }

  scope :accepted, -> { where(board_invitations: { status: :accepted }) }
  scope :pending, -> { where(board_invitations: { status: :pending }) }
  scope :rejected, -> { where(board_invitations: { status: :rejected }) }
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[ show edit update destroy ]

  # GET /boards or /boards.json
  def index
    @boards = current_user.boards.includes(:lists).rank(:row_order)
    @invited_boards = current_user.accepted_boards
    @lists = current_board.lists.includes(:tasks).rank(:row_order) if current_board
  end

  # GET /boards/1 or /boards/1.json
  def show
    @lists = @board.lists
    @boards = current_user.boards.includes(:lists).rank(:row_order)
    switch_board(@board)

    respond_to do |format|
      format.turbo_stream
    end
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards or /boards.json
  def create
    @board = Board.new(board_params)
    @board.user = current_user

    respond_to do |format|
      if @board.save
        switch_board(@board)
        @boards = current_user.boards.includes(:lists).rank(:row_order) 
        format.turbo_stream
        format.html { redirect_to @board, notice: "Board was successfully created." }
        format.json { render :show, status: :created, location: @board }
      else
        format.turbo_stream { 
          render turbo_stream: turbo_stream.update('error-message', partial: 'boards/error'), status: :unprocessable_entity 
        }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1 or /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        @boards = current_user.boards.includes(:lists).rank(:row_order) 
        format.turbo_stream
        format.html { redirect_to @board, notice: "Board was successfully updated." }
        format.json { render :show, status: :ok, location: @board }
      else
        format.turbo_stream { 
          render turbo_stream: turbo_stream.update('error-message', partial: 'boards/error'), status: :unprocessable_entity 
        }
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1 or /boards/1.json
  def destroy
    @board.destroy!

    respond_to do |format|
      format.html { redirect_to boards_path, status: :see_other, notice: "Board was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def board_params
      params.expect(board: [ :name, :user_id, :background ])
    end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<%= link_to board_path(board), data: { turbo_stream: true } do %>
  <li class="my-2 p-1 hover:bg-gray-300 hover:border-l-4 hover:border-sky-500 <%= current_board == board ? 'bg-gray-300 border-l-4 border-sky-500' : ''%>"><%= board.name %></li>
<%end%>

app/views/boards/_board_lists.html.erb
<%= turbo_frame_tag "lists_#{current_board.try(:id)}" do %>
  <div class="top-0 left-60 bottom-0 fixed right-0 overflow-x-auto" id="right-section">
    <% if current_board %>
      <div data-controller="modal" class="flex w-full p-3 mb-2 bg-gray-200">
        <h3 class="text-black font-semibold" id="board-name"><%=current_board.try(:name)%></h3>
        <button
            type="button"
            data-action="click->modal#open"
            class="rounded-md bg-gray-400 px-2 py-1 ml-2 text-xs font-semibold text-white shadow-sm hover:bg-gray-500 cursor-pointer"
            >Edit</button>
        <button
            type="button"
            data-action="click->modal#open"
            data-button-type="invitation"
            class="rounded-md bg-orange-400 px-2 py-1 ml-2 text-xs font-semibold text-white shadow-sm hover:bg-orange-500 cursor-pointer"
            >Invite a Member</button>
        <%= render 'board_invitations/form' %>
        <%= render 'form', board: current_board %>
      </div>
    <%end%>
    
    <%= render 'boards/lists', lists: @lists %>
  </div>
<%end%>

app/views/boards/_boards.html.erb
<% boards.each do |board| %>
  <%= render 'board', board: board %>
<%end%>

app/views/boards/_current_board_lists.html.erb
<%= render lists if lists %>
<% if current_board  %>
  <%= turbo_frame_tag "new_list", src: new_list_path %>
<%else%>
  <h3 class="p-2 bg-orange-400 rounded text-black">No board found! Click on New Board button to create one.</h3>
<%end%>

app/views/boards/_error.html.erb
<span class="text-red-500 text-sm"><%= @board.errors.messages[:name].join(',') %></span>

app/views/boards/_form.html.erb
<!-- Modal Background -->
<div data-modal-target="modal" class="absolute inset-0 top-10 hidden z-[999]" data-action="click->modal#close">
  <div class="bg-white p-5 ml-3 rounded-lg shadow-lg max-w-60">
    <!-- Form with Rails `form_tag` -->
    <%= form_with(model: board, 
                  html: { data: { action: 'click->modal#submit', 'modal-target' => 'form', method: board.new_record? ? 'post' : 'put' } }) do |f| %>
      <div class="mb-4">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'w-full p-2 border rounded', required: true, data: { 'modal-target' => 'nameInput' } %>
        <p id="error-message"></p>
      </div>

      <div class="flex justify-end">
        <%= f.submit 'Save', class: "bg-sky-500 text-white px-2 py-1 rounded cursor-pointer", data: { turbo_disable: true } %>
        <button type="button" data-action-close class="ml-2 bg-gray-400 text-white px-2 py-1 rounded cursor-pointer">Close</button>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/_lists.html.erb
<div class="flex px-2" id="current-board-lists" data-controller="sortable" data-sortable-group-value="lists">
  <%= render 'current_board_lists', lists: @lists %>
</div>

app/views/boards/create.turbo_stream.erb
<%if @board.errors.any? %>
  <%#= turbo_stream.update 'error-message' do %>
    <%# <span class="text-red-500"><%#= @board.errors.messages[:name].join(',') %></span> %>
  <%#end%>
<%else%>
  <%= turbo_stream.update 'boards-container' do %>
    <%= render partial: 'boards' %>
  <%end%>

  <%= turbo_stream.update 'right-section' do %>
    <%= render partial: 'board_lists' %>
  <%end%>
<%end%>

app/views/boards/edit.html.erb
<% content_for :title, "Editing board" %>

<h1>Editing board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Show this board", @board %> |
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/index.html.erb
<div class="flex h-screen">
  <div class="bg-gray-200 border-r-2 border-gray-300 top-0 left-0 bottom-0 w-60 h-full">
    <div class="flex border-b-1 border-gray-400 py-2">
      <div class="px-3 w-15 rounded-sm"><%= image_tag "https://ui-avatars.com/api/?name=#{current_user.name}" %></div>
      <div class="my-1"><%= current_user.name %> </div>
      <div class="ml-auto mr-1"><%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete }, class: 'text-sm text-gray-400 hover:text-red-700' %> </div>
    </div>
    
    <div class="my-5 px-3 relative" data-controller="modal">
      <button
        type="button"
        data-action="click->modal#open"
        class="rounded-md bg-sky-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-sky-500 cursor-pointer"
        >New Board</button>

        <%= render 'form', board: Board.new %>
    </div>
    
    <ul class="my-10 px-3" id="boards-container">
      <b>Your Boards</b>
      <%= render 'boards', boards: @boards %>
    </ul>
    <% if @invited_boards.present? %>
      <ul class="my-10 px-3" id="boards-container">
        <b>Invited Boards</b>
        <%= render 'boards', boards: @invited_boards %>
      </ul>
    <%end%>
  </div>
  
  <%# all lists %>
  <div id="lists-container" class="z-[50]">
    <%= render 'board_lists' %>
  </div>
</div>

app/views/boards/new.html.erb
<% content_for :title, "New board" %>

<h1>New board</h1>

<%= render "form", board: @board %>

<br>

<div>
  <%= link_to "Back to boards", boards_path %>
</div>

app/views/boards/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @board %>

<div>
  <%= link_to "Edit this board", edit_board_path(@board) %> |
  <%= link_to "Back to boards", boards_path %>

  <%= button_to "Destroy this board", @board, method: :delete %>
</div>

app/views/boards/show.turbo_stream.erb
<%= turbo_stream.update "lists-container" do %>
  <%= render partial: "board_lists" %>
<%end%>

<%= turbo_stream.update "boards-container" do %>
  <%= render "boards", boards: @boards %>
<%end%>

app/views/boards/update.turbo_stream.erb
<%= turbo_stream.update 'boards-container' do %>
  <%= render partial: 'boards' %>
<%end%>

<%= turbo_stream.update 'board-name' do %>
  <h3 class="text-black font-semibold" id="board-name"><%=@board.name%></h3>
<%end%>

<%=